import Link from "next/link";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Head from "next/head";
export default function Navbar() {
  return (
    <div className={`${styles.container_fluid} ${styles.for_bg}`}>
      <Head>
        <title>Tree Work, LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        className={`${styles.container} ${styles.forflex} ${styles.ltn_header_transparent}`}
      >
        <div>
          <Link href="/">
            <Image src="/images/logo1.png" alt="logo" width={100} height={92} />
          </Link>
        </div>
        <div className={styles.mainmenu}>
          <Link href="/">
            <a className={`${styles.nav_link} ${styles.active}`}>Home</a>
          </Link>
          <Link href="/about">
            <a className={styles.nav_link}>About</a>
          </Link>
          <Link href="/services">
            <a className={styles.nav_link}>Services</a>
          </Link>
          <Link href="/emergency">
            <a className={styles.nav_link}>Emergency</a>
          </Link>
          <Link href="/testimonials">
            <a className={styles.nav_link}>Testimonials</a>
          </Link>
          <Link href="/blog">
            <a className={styles.nav_link}>Blog</a>
          </Link>
          <Link href="/">
            <a className={styles.nav_link}>Contact</a>
          </Link>
        </div>
      </nav>
    </div>
  );
}
